WORKFLOW="freesurfer"

FREESURFER_DIR="${CODE_DIR}/${WORKFLOW}"
FREESURFER_DATA_DIR="${DERIVATIVES_DIR}/${WORKFLOW}"

SUBJECTSFILE="${FREESURFER_DATA_DIR}/subjectsfile.txt"
JOBSCRIPT_DIR="${JOBSCRIPT_ROOT}/${WORKFLOW}"
LOG_DIR="${LOG_ROOT}/${WORKFLOW}"

CONTAINER="/appl/containers/freesurfer_8.2.0.sif"
LICENSE="${FREESURFER_DIR}/assets/license.txt"
TABULATE_SUBREGIONS="${FREESURFER_DIR}/helpers/tabulate_subregions.py"

NTHREADS=4